(lang dune 2.9)

(name ParadoxModErrorChecker)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Author Name")

(maintainers "Maintainer Name")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name ParadoxModErrorChecker)
 (synopsis "A mod checker for Paradox games")
 (description "A mod checker for Paradox games that helps you find and fix errors in your mods.")
 (depends ocaml dune )
 (tags
  (topics "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/dune-files.html#dune-project
