type lexems=
|Keyword of string
|Bool of bool 
|Float of string
|String of string 
|Tag 
|And 
|Or 
|Not 
|Average_militancy 
|Religion  
|Year  
|Month  
|Allow_multiple_instances   
|Fire_only_once   
|Is_triggered_only   
|Major   
|Immediate   
|Check_variable   
|Which   
|Value   
|Has_global_flag   
|Is_canal_enabled   
|Administration_spending   
|Ai   
|Alliance_with   
|Average_consciousness   
|Badboy   
|Big_producer   
|Blockade   
|Brigades_compare   
|Can_nationalize   
|Can_create_vassals   
|Capital   
|Casus_belli   
|Citizenship_policy   
|Civilization_progress   
|Civilized   
|Colonial_nation   
|Constructing_cb_progress   
|Constructing_cb_type   
|Controls   
|Crime_fighting   
|Crisis_exist   
|Culture_has_union_tag   
|Diplomatic_influence   
|Who   
|Economic_policy   
|Economic_reform_name   
|Education_spending   
|Election   
|Exists   
|Government   
|Great_wars_enabled   
|Have_core_in   
|Has_country_flag   
|Has_country_modifier   
|Has_cultural_sphere   
|Has_leader   
|Has_recently_lost_war   
|Has_unclaimed_cores   
|Ideology   
|Industrial_score   
|In_sphere   
|Invention   
|Involved_in_crisis   
|Is_claim_crisis   
|Is_core   
|Is_cultural_union   
|Is_culture_group   
|Is_disarmed   
|Is_greater_power   
|Is_ideology_enabled   
|Is_independant   
|Is_liberation_crisis   
|Is_mobilised   
|Is_our_vassal   
|Is_possible_vassal   
|Is_secondary_power   
|Is_sphere_leader_of   
|Is_vassal   
|Is_substate   
|Literacy   
|Lost_national   
|Middle_strata_everyday_needs   
|Middle_strata_life_needs   
|Middle_strata_luxury_needs   
|Middle_tax   
|Military_access   
|Military_reform_name   
|Military_score   
|Military_spending   
|Money   
|Nationalvalue   
|National_provinces_occupied   
|Neighbour   
|Num_of_allies   
|Num_of_cities   
|Num_of_ports   
|Num_of_revolts   
|Number_of_states   
|Num_of_substates   
|Num_of_vassals   
|Num_of_vassals_no_substates   
|Owns   
|Part_of_sphere   
|Political_movement_strength   
|Political_reform_name   
|Political_reform_want   
|Poor_strata_everyday_needs   
|Poor_strata_life_needs   
|Poor_strata_luxury_needs   
|Poor_tax   
|Pop_majority_culture   
|Pop_majority_ideology   
|Pop_majority_religion   
|Pop_militancy   
|Prestige   
|Primary_culture   
|Accepted_culture   
|Produces   
|Rank   
|Relation   
|Religious_policy   
|Revolt_percentage   
|Rich_strata_everyday_needs   
|Rich_strata_life_needs   
|Rich_strata_luxury_needs   
|Rich_tax   
|Ruling_party   
|Ruling_party_ideology   
|Slavery   
|Social_reform_name   
|Social_reform_want   
|Social_spending   
|Stronger_army_than   
|Substate_of   
|This_culture_union   
|Total_amount_of_divisions   
|Total_amount_of_ships   
|Total_defensives   
|Total_num_of_ports   
|Total_offensives   
|Total_of_ours_sunk   
|Tag_cond
|Total_sea_battles   
|Total_sunk_by_us   
|Trade_policy   
|Truce_with   
|Unemployment   
|Unemployment_by_type
|Unit_has_leader   
|Unit_in_battle   
|Upper_house   
|Vassal_of   
|War   
|War_exhaustion   
|War_policy   
|War_with   
|Can_build_factory   
|Continent   
|Controlled_by   
|Controlled_by_rebels   
|Country_units_in_province   
|Empty   
|Flashpoint_tension   
|Has_building   
|Has_culture_core   
|Has_empty_adjacent_province   
|Has_empty_adjacent_state   
|Has_factories   
|Has_national_minority   
|Has_pop_type   
|Has_province_flag   
|Has_province_modifier   
|Has_recent_imigration   
|Is_accepted_culture   
|Is_blockaded   
|Is_capital   
|Is_coastal   
|Is_colonial   
|Is_overseas   
|Is_primary_culture   
|Is_state_capital   
|Is_state_religion   
|Life_rating   
|Minorities   
|Owned_by   
|Port   
|Province_control_days   
|Province_id   
|Region   
|State_id   
|Terrain   
|Total_pops   
|Units_in_province   
|Work_available   
|Agree_with_ruling_party   
|Cash_reserves   
|Consciousness   
|Culture   
|Everyday_needs   
|Has_pop_culture   
|Has_pop_religion   
|Life_needs   
|Luxury_needs   
|Militancy   
|Social_movement   
|Strata   
|Assimilate 
|Any_owned 
|Consciousness_effect 
|Militancy_effect 
|Literacy_effect 
|Any_pop_effect 
|Money_effect 
|Move_pop 
|Pop_type 
|Reduce_pop 
|Any_pop 
|Add_core 
|Change_controller 
|Change_province_name 
|Change_region_name 
|Flashpoint_tension_effect 
|Fort 
|Infrastructure  
|Life_rating_effect 
|Naval_base 
|Remove_core 
|Remove_province_modifier 
| rgo_size 
|Secede_province 
|Trade_goods 
|Activate_technology 
|Add_accepted_culture 
|Remove_accepted_culture 
|Add_crisis_interest 
|Add_crisis_temperature 
|Badboy_effect 
|Build_factory_in_capital_state 
|Capital_effect 
|Civilized_effect 
|Kill_leader 
|Nationalvalue_effect 
|Plurality 
|Prestige_effect 
|Prestige_factor 
|Primary_culture_effect 
|Religion_effect 
|Remove_country_modifier_effect 
|Research_points 
|War_exhaustion_effect 
|Years_of_research 
|Nationalize 
|Economic_reform 
|Election_effect 
|Enable_ideology 
|Government_effect 
|Is_slave 
|Military_reform 
|Political_reform 
|Ruling_party_ideology_effect 
|Social_reform 
|Annex_to 
|Create_alliance 
|Create_vassal 
|End_military_access 
|End_war 
|Inherit 
|Leave_alliance 
|Military_access_effect 
|Neutrality 
|Release 
|Release_vassal 
|War_effect 
|Add_tax_relative_income 
|Treasury 
|Change_tag 
|Change_tag_no_core_switch 
|Clr_province_flag 
|Clr_country_flag 
|Clr_global_flag 
|Set_province_flag 
|Set_country_flag 
|Set_global_flag 
|Country_event
|Province_event
